import java.math.BigInteger

//How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

fun main(args: Array<String>) {
    val set = HashSet<BigInteger>()
    (2..100L).forEach { i -> (2..100).mapTo(set) { BigInteger.valueOf(i).pow(it) } }
    println(set.size)
}